{% set name = "colmena" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colmena-{{ version }}.tar.gz
  sha256: 51c2845004023815e868e088c37e02e1dadc43accbaba4ee22ac51dc950b78d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - parsl >=2022
    - pydantic >=2,<3
    - redis-py >=4.3
    - proxystore >=0.5.0

test:
  imports:
    - colmena
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/exalearn/colmena
  summary: 'colmena: Intelligent Steerable Pipelines on HPC'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
